### PR TITLE
Add pulseaudio permission

### PR DESCRIPTION
**Pull request by plata**
see https://github.com/PhoenicisOrg/phoenicis/pull/1841

### CODE REVIEW

**Comment by plata** [comment]
@barthalion is it possible to enable branch protection such that PRs can only be merged after the flathub build is successful and the PR has been reviewed? I think I don't have the rights to do so. Also I would like to enforce "squash and merge" and disable the wiki.

**Comment by TingPing** [comment]
@plata 	Done.

**Comment by plata** [comment]
@TingPing thanks.

**Comment by plata** [comment]
@madoar can you approve?

**Comment by AsciiWolf** [comment]
Looks good.

**Comment by plata** [comment]
@madoar @qparis can one of you please approve this so that I can merge?

**Review by qparis — APPROVED** [review]

**Pull request merged**
